### ISSUE TITLE
Wrong coordinates for Mari

### ISSUE THREAD

**Issue by olcsheehan** [D-PLACE/dplace-dataset-ea#1]
The coordinates provided for Mari (xd568, Ch4) are 43°N, 46°E. These coordinates are the same as those provided for Chechen (xd583, Ci7), which are accurate. The Mari live much further north, in and around the Republic of Mari El (about 56°30' N, 48°E) in Russia. The region should also be changed from 'Caucasus' to 'Eastern Europe'.

**Comment by xrotwang** [comment]
via @olcsheehan 

> Mari (Ch4, xd568) have been placed in the Caucasus region at 43.00 N, 46.00 E. This is a long way south and slightly west of the real location of the Mari (about 56.5 N, 48.00 E, based on the location of the Republic of Mari El). The location currently provided for Mari is the same as for Chechen (Ci7, xd583), and since the original name of Mari in the EA was Cheremis, I wonder if some data accidentally got copied from one row to another.
