### ISSUE TITLE
Gujarati Focal Year (Part 2)

### ISSUE THREAD

**Issue by olcsheehan** [D-PLACE/dplace-dataset-ea#9]
Hi all,

Back in October I raised the issue of the focal year for Gujarati being incorrect - 1136 instead of 1920. I notice that the 'principal year to which the data refer' has been changed to 1920, which is great. However, the focal year attached to all of the variables is still 1136. I just wanted to check that there is a plan to change these too. The year 1136 has no basis in either of the sources cited for this society, which both refer to Gujarat in the twentieth century. 

Best wishes,

Oliver Sheehan

**Comment by xrotwang** [comment]
I just released a fixed version of this dataset. I don't know yet when I will get around to include this fix in the CLDF aggregated data - and hence the website.
